export default {
	GET_USER_DETAILS_REQUEST: "GET_USER_DETAILS_REQUEST",
	TOGGLE_USER_INFO_LOADING: "TOGGLE_USER_INFO_LOADING",
	STRIPE_CODE_VERIFICTION_REQUEST: "STRIPE_CODE_VERIFICTION_REQUEST",

	UPDATE_USER_NAME: "UPDATE_USER_NAME",
	UPDATE_PROFILE_PHOTO: "UPDATE_PROFILE_PHOTO",
};
