export default {
    ADD_ADDRESS_REQUEST: 'ADD_ADDRESS_REQUEST',
    GET_SAVED_ADDRESS_REQUEST: 'GET_SAVED_ADDRESS_REQUEST',
    GET_SAVED_ADDRESS_SUCCESS: 'GET_SAVED_ADDRESS_SUCCESS',
    SET_DEFAULT_ADDRESS: 'SET_DEFAULT_ADDRESS',
    DELETE_ADDRESS_REQUEST: 'DELETE_ADDRESS_REQUEST',
};
