export default {
    ADD_ADDRESS_REQUEST: 'ADD_ADDRESS_REQUEST',
    GET_SAVED_ADDRESS_REQUEST: 'GET_SAVED_ADDRESS_REQUEST',
    GET_SAVED_ADDRESS_SUCCESS: 'GET_SAVED_ADDRESS_SUCCESS',
    SET_DEFAULT_ADDRESS: 'SET_DEFAULT_ADDRESS',
    DELETE_ADDRESS_REQUEST: 'DELETE_ADDRESS_REQUEST',

    HANDLE_CHECKOUT_REQUEST: 'HANDLE_CHECKOUT_REQUEST',

    HANDLE_CHECKOUT_LOADING: 'HANDLE_CHECKOUT_LOADING',
    HANDLE_AUCTION_CHECKOUT_REQUEST: 'HANDLE_AUCTION_CHECKOUT_REQUEST',
    VALIDATE_PROMO_CODE: 'VALIDATE_PROMO_CODE',
    PROMO_VALIDATION_SUCCESS: 'PROMO_VALIDATION_SUCCESS',
    RESET_PROMO: 'RESET_PROMO',
};
