export default {
    GET_AUCTION_PRODUCTS: 'GET_AUCTION_PRODUCTS',
    GET_AUCTION_PRODUCTS_SUCCESS: 'GET_AUCTION_PRODUCTS_SUCCESS',
    GET_AUCTION_PRODUCTS_ERROR: 'GET_AUCTION_PRODUCTS_ERROR',

    GET_AUCTION_LISTING_BY_PRODUCT: 'GET_AUCTION_LISTING_BY_PRODUCT',
    GET_AUCTION_LISTING_BY_PRODUCT_AND_GRADE_SUCCESS:
        'GET_AUCTION_LISTING_BY_PRODUCT_AND_GRADE_SUCCESS',
};
